language: node_js
node_js:
- 11.12.0
notifications:
  email:
    on_success: change
    on_failure: always
before script:
- npm install -g @angular/cli@~7.3.7
before_deploy:
- ng build --prod
deploy:
  provider: heroku
  strategy: api
  api_key:
    secure: krBkNAXvgookTlFQ/kMjSs6S6u1WByPKIX3FTm86vPE0CmY+6u6tkWdW5HceH4ahv5lCXB+u0fPKtye4albWjHpxMiwK+NbHcDYgLC1RmFNbuSs6sF9Hwxy4QkmTNzbllb389vz7Jm2I3nztCc3+ArR1H5A1J7iyxhkhJrqx3IaBSQhEW4q5Dkw9CNh55OWsv6PBB6EnVc3XlNRsKPdLJsctc/96LmQZMJhnVVpVd/S/4QNJ1Xr6bLhg2BbCXh5qWTZWZM19+Hi1yDc4/K2HABsBU6y2BuzJNDW0DcHV50a6ikVeygLS8eeePBU2quFTffse/YWgAYLoOZV3akvrhC3D6z/a2+okbJatWvhfXEI4dSH9kwHDcu7Zs5sWDDWhdIndkKSNRO622U8q6J9wQc+8y6hYGCbdEodlH3ndPKXSXIEm81/yFw+rf+mZn0qpTJSq6wNkaoBUVuqszaxLjwEjCquZfZkMTuLt3ZHzYlW/RYnpzGPZVXGetmJQIcZp66RF4pYK5RnttPDhiS3YXDVTbo0aybqFo0GTJhepwvR7aRVvRnddLD6LhPhngFAIXjHa6dm2DFRPDhzBptLeVzJsg/qUd3g/tIwic31/J/c0ikY+h2ecm4PFQkza0Kt3MFguHLYjYlxtlwmurVdD7kWIYI3ODbqW2LqCKrIviO4=
  skip_cleanup: true
  app: microposts-ui
  on:
    repo: cdelmoral/microposts-ui
    branch: master
